#include <gtest/gtest.h>

// This header is generated by CMake configure_file() from
// cmake/InstallConfig.h.in. It contains build-time CMake variables
// that the tests verify at runtime.
#include "InstallConfig.h"

#include <cstring>
#include <string>

namespace {

// ---------------------------------------------------------------------------
// Test 1: project() has VERSION defined
// ---------------------------------------------------------------------------
TEST(InstallRulesTest, ProjectVersionIsDefined) {
    const std::string version = DBP_PROJECT_VERSION;
    EXPECT_FALSE(version.empty())
        << "PROJECT_VERSION must be set in the project() call";
}

TEST(InstallRulesTest, ProjectVersionMatchesExpectedFormat) {
    const std::string version = DBP_PROJECT_VERSION;
    // Expect semver-like "major.minor.patch"
    auto dot_count = std::count(version.begin(), version.end(), '.');
    EXPECT_GE(dot_count, 2)
        << "Version should be in major.minor.patch format, got: " << version;
}

TEST(InstallRulesTest, ProjectVersionIs105) {
    EXPECT_STREQ(DBP_PROJECT_VERSION, "1.0.5");
}

// ---------------------------------------------------------------------------
// Test 2: CPack configuration exists
// ---------------------------------------------------------------------------
TEST(InstallRulesTest, CPackIsConfigured) {
    EXPECT_EQ(DBP_CPACK_CONFIGURED, 1)
        << "CPack must be configured with include(CPack)";
}

TEST(InstallRulesTest, CPackPackageNameIsSet) {
    const std::string name = DBP_CPACK_PACKAGE_NAME;
    EXPECT_FALSE(name.empty())
        << "CPACK_PACKAGE_NAME must be set";
}

TEST(InstallRulesTest, CPackPackageVersionMatchesProjectVersion) {
    const std::string cpack_version = DBP_CPACK_PACKAGE_VERSION;
    EXPECT_EQ(cpack_version, DBP_PROJECT_VERSION)
        << "CPACK_PACKAGE_VERSION must match PROJECT_VERSION";
}

TEST(InstallRulesTest, CPackVendorIsSet) {
    const std::string vendor = DBP_CPACK_PACKAGE_VENDOR;
    EXPECT_FALSE(vendor.empty())
        << "CPACK_PACKAGE_VENDOR must be set";
}

// ---------------------------------------------------------------------------
// Test 3: Install rules exist for executables
// ---------------------------------------------------------------------------
TEST(InstallRulesTest, InstallRulesAreDefined) {
    EXPECT_EQ(DBP_INSTALL_RULES_DEFINED, 1)
        << "install() rules must be configured";
}

TEST(InstallRulesTest, InstallConfigDirectoryIsSet) {
    const std::string dir = DBP_INSTALL_CONFIG_DIR;
    EXPECT_FALSE(dir.empty())
        << "Install configuration directory must be set";
}

// ---------------------------------------------------------------------------
// Test 4: LICENSE file exists for CPack
// ---------------------------------------------------------------------------
TEST(InstallRulesTest, LicenseFileExists) {
    const std::string license_path = DBP_LICENSE_FILE_PATH;
    EXPECT_FALSE(license_path.empty())
        << "CPACK_RESOURCE_FILE_LICENSE must be set";
}

} // namespace
